[package]
name = "task-scheduler"
version = "0.1.0"
edition = "2021"

[lib]
name = "task_scheduler"
path = "src/lib.rs"

[[bin]]
name = "task-scheduler"
path = "src/main.rs"

[dependencies]
tonic = { version = "0.10", default-features = false, features = [
    "transport",
    "codegen",
    "prost",
] }
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "sync"] }
prost = "0.12"
prost-types = "0.12"
parking_lot = "0.12"
dashmap = "5.5"
rayon = "1.10"
ahash = "0.8"
lru = "0.12"
futures = "0.3"
once_cell = "1.19"
thiserror = "1.0"
task-macro = { path = "./task-macro" }
ctor = "0.2"
clap = { version = "4.5", features = ["derive"] }

[build-dependencies]
tonic-build = "0.10"

[dev-dependencies]
tokio-test = "0.4"

[workspace]
members = ["task-macro"]
